default_install_hook_types:
  # Mandatory to install both pre-commit and pre-push hooks
  - pre-commit
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: ['mypy==0.910']

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ['flake8==3.9.2']

  - repo: local
    hooks:
      - id: ruff
        name: Formatting (ruff)
        entry: make format-code
        language: system
        types: [python]
        stages: [commit]
      - id: ruff-check
        name: Linter (ruff)
        entry: make check-format-code
        language: system
        types: [python]
        stages: [commit]
      - id: mypy
        name: Type checking (mypy)
        entry: make type-check
        pass_filenames: false
        language: system
        types: [python]
        stages: [commit]
      - id: unit-tests
        name: Unit tests (pytest)
        entry: make test
        language: system
        types: [python]
        stages: [commit]
      - id: docs
        name: Build docs
        entry: make build-docs
        language: system
        types: [python]
        stages: [commit]