- name: Create pod and run containers
  hosts: localhost
  vars:
    # The desired state of the containers (started/stopped)
    container_state: started

    # Set to true to use GPUs, false to not use GPUs
    use_gpus: false

    # Set to true to start only the development container
    start_dev_only: false

    # Pod name derived from environment variable
    pod_name: "{{ lookup('env', 'POD_NAME') | regex_replace('/', '_') }}"

    # Image used for the development container
    dev_image: marcorepettocertx/dev:0.0.5

    # Common volumes to be mounted in the development container
    common_volumes:
      - ./nirmatai_sdk:/app/nirmatai_sdk
      #- ./data:/app/data  # Uncomment if needed
      #- ./experiments:/app/experiments  # Uncomment if needed
      - ./docs:/app/docs
      - ./htmlcov:/app/htmlcov
      - ./pyproject.toml:/app/pyproject.toml

    # Common environment variables for the development container
    common_env:
      MLFLOW_TRACKING_URI: "http://host.containers.internal:5000"
      POD_NAME: "{{ pod_name }}"
      PGPT_OLLAMA_LLM_MODEL: "{{ lookup('env', 'PGPT_OLLAMA_LLM_MODEL') | default('mistral') }}"
      PGPT_OLLAMA_EMBEDDING_MODEL: "{{ lookup('env', 'PGPT_OLLAMA_EMBEDDING_MODEL') | default('nomic-embed-text') }}"
      PGPT_RAG_SIMILARITY_TOP_K: "{{ lookup('env', 'PGPT_RAG_SIMILARITY_TOP_K') | default('2') }}"

  tasks:
    # Create a pod if not starting the dev container only
    - name: Create pod
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: "{{ container_state }}"
        recreate: true
        ports:
          - 8000:8080
      when: not start_dev_only | bool

    # Create a development container without GPU
    - name: Create dev container
      containers.podman.podman_container:
        name: "{{ pod_name }}_dev"
        image: "{{ dev_image }}"
        state: "{{ container_state }}"
        detach: true
        pod: "{{ pod_name if not start_dev_only else None }}"
        volume: "{{ common_volumes }}"
        env: "{{ common_env }}"
      when: not use_gpus | bool

    # Create a development container with GPU
    - name: Create dev container with GPU
      containers.podman.podman_container:
        name: "{{ pod_name }}_dev"
        image: "{{ dev_image }}"
        state: "{{ container_state }}"
        detach: true
        pod: "{{ pod_name if not start_dev_only else None }}"
        device:
          - "nvidia.com/gpu=all"
        volume: "{{ common_volumes }}"
        env: "{{ common_env }}"
      when: use_gpus | bool
