FROM python:3.12-bullseye

# Install ping and nslookup
RUN apt-get update && apt-get install -y iputils-ping dnsutils

# Set python alias
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set environment variable to include the current directory in PYTHONPATH
ENV PYTHONPATH=/app

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml file to the working directory
COPY pyproject.toml .

# Install the dependencies
RUN pip install .[dev,docs]

# Keep the container running
CMD tail -f /dev/null
