name: Forgejo tests  # The name of the GitHub Actions workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:  # Trigger forgejo workflow on pull requests

jobs:
  test:
    runs-on: docker
    steps:
      - run: echo All Good
