name: Static tests

on: pull_request

jobs:
  setup:
    runs-on: podman
    env:
      POD_NAME: forgejo
    steps:
      - name: Install dependencies
        run: dnf install -y nodejs git make ansible
      - name: Install ansible-galaxy
        run: ansible-galaxy collection install containers.podman
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up dev container
        run: make run-dev

  checks:
    runs-on: podman
    env:
      POD_NAME: forgejo
    needs: setup
    strategy:
      matrix:
        ci_step:
          - ansible-lint
          - format-check
          - type-check
    steps:
      - name: Install dependencies
        run: dnf install -y nodejs git make ansible
      - name: Install ansible-galaxy
        run: ansible-galaxy collection install containers.podman
      - name: Checkout
        uses: actions/checkout@v4
      - name: run dev container
        run: make run-dev
      - name: Static tests
        run: make ${{ matrix.ci_step }}

  docs:
    runs-on: podman
    env:
      POD_NAME: forgejo
    needs: setup
    steps:
      - name: Install dependencies
        run: dnf install -y nodejs git make ansible
      - name: Install ansible-galaxy
        run: ansible-galaxy collection install containers.podman
      - name: Checkout
        uses: actions/checkout@v4
      - name: run dev container
        run: make run-dev
      - name: Build docs
        run: make build-docs
      - name: Archive docs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docs
          path: docs/build/

  all_checks_passed:
    needs:
      - checks
      - docs
    runs-on: docker
    steps:
      - run: echo "All checks passed and docs built successfully!"
