name: Label issues  # Name of the GitHub Actions workflow

on:
  issues:
    types:
      - reopened  # Trigger workflow when an issue is reopened
      - opened  # Trigger workflow when a new issue is opened

jobs:
  label_issues:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job
    permissions:
      issues: write  # Grant write permissions to issues
    steps:
      - name: Check if label exists  # Step to check if the "triage" label exists
        id: check_label
        run: |
          if ! gh label list --repo ${{ github.repository }} | grep -q "^triage$"; then
            echo "Label 'triage' does not exist, creating it."
            gh label create "triage" --description "Issues that need triage" --color "#ffffff" --repo ${{ github.repository }}
          else
            echo "Label 'triage' exists."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label issue  # Step to label the issue
        run: gh issue edit ${{ github.event.issue.number }} --add-label "triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
